import { DATE_VALUES } from './filterOptions'
import { FILTER_TYPES } from './filterTypes'

export const DEFAULT_EMPTY_FILTERS = {
  [FILTER_TYPES.DATE]: DATE_VALUES.ANY,
  [FILTER_TYPES.COMPANY]: [],
  [FILTER_TYPES.EXPERIENCE]: [],
  [FILTER_TYPES.MODE]: [],
  [FILTER_TYPES.TYPE]: [],
}

export const DEFAULT_REFERENCE_FILTERS = {
  [FILTER_TYPES.DATE]: null,
  [FILTER_TYPES.COMPANY]: null,
  [FILTER_TYPES.EXPERIENCE]: null,
  [FILTER_TYPES.MODE]: null,
  [FILTER_TYPES.TYPE]: null,
}
